### ISSUE TITLE
I have the honor of submitting the first issue，and i want to ask what dose ". l and .y“ file meaning？

### ISSUE THREAD

**Issue by nealwang123** [ihedvall/dbclib#7]

**Comment by Murmele** [comment]
They are used by flex and bison to generate the actual c code out of it.

**Comment by ihedvall** [comment]
These files are flex and bison files. Flex.exe and Bison.exe are executables that generate h/cpp files. Flex files uses the *. extension while the bison uses the *.y extension. Flex/Bison needs to run before the remaining compiler compiles the remaining files.

You need to install Flex and Bison on your computer if you want to compile the DBC library. It is little bit tricky depending on operating system. WinFlexBison for windows.

**Comment by ihedvall** [comment]
I think Murmele mentioned earlierthat generating flex and bison cpp files are not needed in most compilation unless you change the lex or yacc files.
 Maybe its good time to solve this issue so most "users" doesn't need the flex and bison. I can try some cmake tricks.

**Comment by ihedvall** [comment]
Well I didn't succes on this mission due to the FlexLexer.h file that the FlexBison installtion includes. So the conclusion is that the WinFlexBison (windows) and the flex-dev needs to be installed on the build computer.
The FlexLexer.h is used for the C++ generation. A new cmake flag (DBC_YACC OFF default) disable the generation of FLEX and BISON files.
